# Generated by Django 4.1.5 on 2025-05-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('current_bookings', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=10)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '강사 스케줄',
                'verbose_name_plural': '강사 스케줄 관리',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LessonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sessions_count', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '레슨 상품 (강습권)',
                'verbose_name_plural': '레슨 상품 (강습권) 관리',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PracticeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NOSHOW', 'No-Show')], db_index=True, default='RESERVED', max_length=10)),
                ('is_waiting', models.BooleanField(db_index=True, default=False)),
                ('queue_position', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '자율 연습 예약',
                'verbose_name_plural': '자율 연습 예약 관리',
                'ordering': ['practice_session', 'is_waiting', 'queue_position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('current_bookings', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '자율 연습 세션',
                'verbose_name_plural': '자율 연습 세션 관리',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_order', models.PositiveIntegerField(blank=True, null=True)),
                ('is_theory', models.BooleanField(default=False)),
                ('is_waiting', models.BooleanField(db_index=True, default=False)),
                ('queue_position', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NOSHOW', 'No-Show')], db_index=True, default='RESERVED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '레슨 세션 예약',
                'verbose_name_plural': '레슨 세션 예약 관리',
                'ordering': ['schedule', 'queue_position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_total', models.PositiveIntegerField()),
                ('sessions_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('UNUSED', 'Unused'), ('PARTIALLY_USED', 'Partially Used'), ('FULLY_USED', 'Fully Used'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='UNUSED', max_length=20)),
                ('valid_until', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='buccl_lessons.lessonproduct')),
            ],
            options={
                'verbose_name': '레슨 티켓',
                'verbose_name_plural': '레슨 티켓 관리',
                'ordering': ['-created_at'],
            },
        ),
    ]
