# Generated by Django 4.1.5 on 2025-05-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buccl_main', '0001_initial'),
        ('buccl_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_ticket', to='buccl_main.order'),
        ),
    ]
