# Generated by Django 4.1.5 on 2025-05-22 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buccl_main', '0001_initial'),
        ('buccl_lessons', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionreservation',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='buccl_lessons.instructorschedule'),
        ),
        migrations.AddField(
            model_name='sessionreservation',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='buccl_lessons.ticket'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='base_schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='based_practice_session', to='buccl_lessons.instructorschedule'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buccl_main.location'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buccl_main.sport'),
        ),
        migrations.AddField(
            model_name='practicereservation',
            name='practice_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='buccl_lessons.practicesession'),
        ),
        migrations.AddField(
            model_name='practicereservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonproduct',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_specific_products', to='buccl_main.sport'),
        ),
        migrations.AddField(
            model_name='instructorschedule',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorschedule',
            name='lesson_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='buccl_lessons.lessonproduct'),
        ),
        migrations.AddField(
            model_name='instructorschedule',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buccl_main.location'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionreservation',
            unique_together={('ticket', 'schedule')},
        ),
        migrations.AlterUniqueTogether(
            name='practicereservation',
            unique_together={('user', 'practice_session')},
        ),
        migrations.AddConstraint(
            model_name='instructorschedule',
            constraint=models.UniqueConstraint(fields=('instructor', 'date', 'start_time', 'location'), name='unique_instructor_schedule_slot'),
        ),
        migrations.AddConstraint(
            model_name='instructorschedule',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='check_start_end_time'),
        ),
    ]
