# Generated by Django 4.1.5 on 2025-05-22 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buccl_lessons', '0003_initial'),
        ('buccl_main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelproduct',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_travel_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buccl_main.classreview'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buccl_main.classproduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='class_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_products', to='buccl_main.classproduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='lesson_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_products', to='buccl_lessons.lessonproduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buccl_main.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='travel_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_products', to='buccl_main.travelproduct'),
        ),
        migrations.AddField(
            model_name='paymentnetcancelresponse',
            name='net_cancel_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='buccl_main.paymentnetcancelrequest'),
        ),
        migrations.AddField(
            model_name='paymentnetcancelresponse',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_cancel_responses', to='buccl_main.payment'),
        ),
        migrations.AddField(
            model_name='paymentnetcancelrequest',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_cancel_requests', to='buccl_main.payment'),
        ),
        migrations.AddField(
            model_name='paymentcaptureresponse',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capture_response', to='buccl_main.payment'),
        ),
        migrations.AddField(
            model_name='paymentcapturerequest',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capture_request', to='buccl_main.payment'),
        ),
        migrations.AddField(
            model_name='paymentcancelresponse',
            name='payment_cancel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_response', to='buccl_main.paymentcancel'),
        ),
        migrations.AddField(
            model_name='paymentcancelrequest',
            name='payment_cancel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_request', to='buccl_main.paymentcancel'),
        ),
        migrations.AddField(
            model_name='paymentcancel',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='buccl_main.payment'),
        ),
        migrations.AddField(
            model_name='paymentauthresponse',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_response', to='buccl_main.payment'),
        ),
        migrations.AddField(
            model_name='paymentauthrequest',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_request', to='buccl_main.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='buccl_main.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buccl_main.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='locations', to='buccl_main.sport'),
        ),
        migrations.AddField(
            model_name='classreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='buccl_main.classproduct'),
        ),
        migrations.AddField(
            model_name='classreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
