# Generated by Django 4.1.5 on 2025-05-22 10:24

import buccl_user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buccl_main', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='이름')),
                ('hp', models.CharField(db_index=True, max_length=12, null=True, unique=True, verbose_name='휴대폰번호')),
                ('user_email', models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='이메일')),
                ('user_gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=10, null=True, verbose_name='성별')),
                ('user_birthday', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('auth', models.CharField(max_length=6, null=True, verbose_name='인증번호')),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='가입일')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='이용약관동의')),
                ('age_confirmed', models.BooleanField(default=False, verbose_name='연령확인')),
                ('privacy_accepted', models.BooleanField(default=False, verbose_name='개인정보수집동의')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 계정 관리',
                'db_table': 'buccl_user',
                'ordering': ['-date_joined', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='AuthSMS',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hp', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='휴대폰번호')),
                ('auth', models.IntegerField(verbose_name='인증번호')),
            ],
            options={
                'db_table': 'AUTH_TB',
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_levels', to='buccl_main.sport')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255)),
                ('certificate_file', models.FileField(upload_to=buccl_user.models.unique_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_certificates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '자격증 업로드',
                'verbose_name_plural': '자격증 업로드 관리',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buccl_user.userlevel', verbose_name='User 등급'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
